// "林伯慎老師實驗室", "林伯慎老師實驗室",
// "Special Topic", "Special Topic", 

var names = [
    // "CS", "Nigus"
    // "Zephaniah", "CS", 
    // "Jason", "Zephaniah", 
    // "Tim", "Jason", 
    // "林芳義", "Tim",
    // "許家瑋", "林芳義",
    // "許瓊方", "許家瑋",
    // "廖庭婕", "許瓊方",
    // "何思嫺", "廖庭婕",
    // "Haile", "何思嫺", 
    // "Marcell", "Haile", 
    // "Jack", "Marcell", 
    // "Hank", "Jack", 
    // "Summer", "Hank", 
    // "Allen", "Summer", 
    // "Jenny", "Allen",
    // "Vicky", "Jenny", 
    // "Edwin", "Vicky", 
    // "Molion", "Edwin", 
    // "吳家霖", "Molion",
    // "葉三吉", "吳家霖",
    // "Nigus", "葉三吉",
    // "老師上課", "老師上課",
    // "CS", "Nigus"
    // "Zephaniah", "CS", 
    // "Jason", "Zephaniah", 
    "林芳義", "Jason", 
    "Special Topic", "Special Topic", 
    "x", "Tim",
    "林伯慎老師實驗室", "林伯慎老師實驗室",
    "許家瑋", "林芳義",
    "許瓊方", "許家瑋",
    "廖庭婕", "許瓊方",
    "何思嫺", "廖庭婕",
    "Haile", "何思嫺", 
    "Marcell", "Haile", 
    "Jack", "Marcell", 
    "X", "X", 
    "林伯慎老師實驗室", "林伯慎老師實驗室",
    "Hank", "Jack", 
    "Summer", "Hank", 
    "Allen", "Summer", 
    "Jenny", "Allen",
    "Vicky", "Jenny",
    "Edwin", "Vicky",
    "Molion", "Edwin", 
    "吳家霖", "Molion", 
    "X", "X", 
    "葉三吉", "吳家霖",
    "老師上課", "老師上課", 
    "李一峯", "葉三吉", 
    "X", "X", 
    "Nigus", "李一峯", 
    "X", "X",
    "Haile", "Nigus", 
    "X", "X", 
    "Marcell", "Haile", 
    "Jack", "Marcell", 
    "X", "X",
    "Hank", "Jack", 
    "X", "X", 
    "Summer", "Hank", 
    "Allen", "Summer", 
    "Jenny", "Allen",
    "Vicky", "Jenny", 
    "張宗雅", "Vicky", 
    "Edwin", "張宗雅", 
    "Molion", "Edwin", 
    "Rini", "Molion",
    "X", "X", 
    "姿廷", "Rini", 
    "雯筑", "姿廷", 
    "吳家霖", "雯筑", 
    "葉三吉", "吳家霖",
    "X", "X", 
    "老師上課", "老師上課", 
    "X", "X", 
    "X", "X"
];

/*
var names = [
    "Vicky", "Jenny", 
    "Edwin", "Vicky", 
    "Molion", "Edwin", 
    "林伯慎老師實驗室", "林伯慎老師實驗室",
    "老師上課", "老師上課",
    "吳家霖", "Molion", 
    "葉三吉", "吳家霖", 
    "李一峯", "葉三吉",
    "Nigus", "李一峯", 
    "Haile", "Nigus", 
    "Marcell", "Haile", 
    "Jack", "Marcell", 
    "X", "X",
    "Hank", "Jack", 
    "Summer", "Hank", 
    "Allen", "Summer", 
    "Jenny", "Allen",
    "Vicky", "Jenny",
    "Edwin", "Vicky",
    "Molion", "Edwin", 
    "吳家霖", "Molion", 
    "X", "X", 
    "葉三吉", "吳家霖",
    "老師上課", "老師上課", 
    "李一峯", "葉三吉", 
    "X", "X", 
    "Nigus", "李一峯", 
    "X", "X",
    "Haile", "Nigus", 
    "X", "X", 
    "Marcell", "Haile", 
    "Jack", "Marcell", 
    "X", "X",
    "Hank", "Jack", 
    "X", "X", 
    "Summer", "Hank", 
    "Allen", "Summer", 
    "Jenny", "Allen",
    "Vicky", "Jenny", 
    "張宗雅", "Vicky", 
    "Edwin", "張宗雅", 
    "Molion", "Edwin", 
    "Rini", "Molion",
    "X", "X", 
    "姿廷", "Rini", 
    "雯筑", "姿廷", 
    "吳家霖", "雯筑", 
    "葉三吉", "吳家霖",
    "X", "X", 
    "老師上課", "老師上課", 
    "X", "X", 
    "X", "X"
];
*/